source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/summertian4/ZLYSpec.git'

platform :ios, ‘8.0’

target 'DemoProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoProject
  pod 'ZLYAccountModule', :path => '../ZLYAccountModule'
  pod 'ZLYPublicModule', '~> 0.0.1'

end
